### ISSUE TITLE
API Inconsistencies

### ISSUE THREAD

**Issue by OtaK** [wireapp/core-crypto#10]
* https://github.com/wireapp/core-crypto/blob/develop/crypto/src/conversation.rs#L220 takes KeyPackages, but should take KeyPackageRefs as an argument.
	* So we should add a newtype to encapsulate Keypackagerefs somehow
* Adjust the configuration required for https://github.com/wireapp/core-crypto/blob/develop/crypto/src/conversation.rs#L150

**Comment by typfel** [comment]
>https://github.com/wireapp/core-crypto/blob/develop/crypto/src/conversation.rs#L220 takes KeyPackages, but should take KeyPackageRefs as an argument.

Do you need the KeyPackageRefs? Isn't it enough for me to give you the client the IDs and you'll look up the key package ref internally?

**Comment by OtaK** [comment]
> > [https://github.com/wireapp/core-crypto/blob/develop/crypto/src/conversation.rs#L220](https://github.com/wireapp/core-crypto/blob/develop/crypto/src/conversation.rs?rgh-link-date=2022-03-29T07%3A26%3A38Z#L220) takes KeyPackages, but should take KeyPackageRefs as an argument.
> 
> Do you need the KeyPackageRefs? Isn't it enough for me to give you the client the IDs and you'll look up the key package ref internally?

That's what I'm doing right now (see https://github.com/wireapp/core-crypto/blob/develop/crypto/src/conversation.rs#L234-L236)
That's why you're able to send a dummy map of client IDs to nothing - it's because I'm ignoring the keypackages and retrieving the KPRefs from the MLS group itself via Client ID matching.

If client ids are enough I'm fine with it. That can become as simple as providing a vec of ClientIDs.

Starting to think that the whole `ConversationMember` thing - it was supposed to be an abstraction to ease managing Wire users with their N clients - is just causing more confusion/problems than it solves.
