### ISSUE TITLE
Externally-generated Clients

### ISSUE THREAD

**Issue by OtaK** [wireapp/core-crypto#11]
Steps: 
* Generate a keypair (subtle crypto for instance)
* Let the library consumer create the "Client" on the MLS DS
* Provide an API to create the local CoreCrypto Client using that new Client ID + previously generated keypair.

**Comment by rohan-wire** [comment]
OpenMLS already made public an API to do their part of this.

**Comment by OtaK** [comment]
Slated for 0.4.0 release
