### ISSUE TITLE
Better testing strategy

### ISSUE THREAD

**Issue by beltram** [wireapp/core-crypto#77]
The goal is to have better tests, better coverage but first, tests should be easy to write and maintain

Acceptance criterias:
* provide helpers to write tests on conversations (`MlsConversation`)
* Move all test fixtures in a dedicated crate (`crypto-fixtures` ?)
* All tests involving a conversation must be tested both on `MlsCentral` and `MlsConversation`
* All tests must be executed in WASM

**Comment by istankovic** [comment]
Not relevant anymore, closing.
