### ISSUE TITLE
iOS Backgrounding fix prevents using several databases / accounts

### ISSUE THREAD

**Issue by OtaK** [wireapp/core-crypto#95]
See: https://github.com/wireapp/core-crypto/blob/develop/keystore/src/connection/platform/generic/mod.rs#L101

The keystore salt is stored within a single generic password - without qualifying it for the current database.
This would prevent using multiple accounts/databases/keystores

**Comment by rohan-wire** [comment]
@comawill please think about the implications of this.

**Comment by comawill** [comment]
From my point of view the only reasonable solution here is to provide a way to read and store the database specific salt inside of the referenced function (or something equivalent).

`cipher_salt` is used with PBKDF2-HMAC-SHA512 to derive the aes key from the provided passphrase, reusing the salt would compromise the function of the salt here.

**Comment by OtaK** [comment]
I think it s much simpler to solve. We could just prefix the name of the single generic password (stored in the keychain) with either the database name or the client id. This way we d avoid overwriting the salt
